### ISSUE TITLE
    load_checkpoint(model, checkpoint, map_location='cpu') NameError: name 'load_checkpoint' is not defined

### ISSUE THREAD

**Issue by monacv** [yeliudev/ConsNet#2]
thanks a lot for great documentation. got an error in this step
![Screenshot from 2021-04-08 03-19-35](https://user-images.githubusercontent.com/76495162/113984629-4d18b000-9819-11eb-9755-4a91ba924fa1.png)
```
(consnet) mona@goku:~/research/code/ConsNet$ python tools/build_dataset.py --checkpoint checkpoints/
Traceback (most recent call last):
  File "tools/build_dataset.py", line 280, in <module>
    main()
  File "tools/build_dataset.py", line 259, in main
    model = build_detector(cfg.model, args.checkpoint)
  File "/home/mona/venv/consnet/lib/python3.8/site-packages/consnet/models/builder.py", line 50, in build_detector
    load_checkpoint(model, checkpoint, map_location='cpu')
NameError: name 'load_checkpoint' is not defined

```

**Comment by yeliudev** [comment]
It seems that the dependencies of full version are not installed correctly. Did you install `consnet` from PyPI? If so, please uninstall it and re-install it from source following [this part](https://github.com/yeliudev/ConsNet#install-from-source). The PyPI version is only designed for HICO-DET APIs but not for training or testing the models.

**Comment by yeliudev** [comment]
Also, `<path-to-checkpoint>` should be a complete path to the object detetor's `.pth` file, e.g. `checkpoints/faster_rcnn_r50_fpn_3x_coco-26df6f6b.pth`.

**Comment by yeliudev** [comment]
Closing this issue due to lack of activity. Please feel free to re-open it if you have any further questions.

**Comment by hannajiang** [comment]
Hi, I also meet this problem, and I install consnet from source. When I move code `from nncore.engine import load_checkpoint, set_random_seed`  in models/builder.py from try except module, this problem will be solved; but I meet another problem, 
![image](https://user-images.githubusercontent.com/69292661/133880116-26fd27d9-2343-43af-9f84-606087ef6a86.png)

**Comment by yeliudev** [comment]
May I ask that which pytorch, mmdet and nncore version are you using?

**Comment by hannajiang** [comment]
consnet            1.0.5     /home/jh/code/CosNet
torch              1.8.1
mmdet              2.11.0
nncore             0.2.6

**Comment by yeliudev** [comment]
nncore 0.2.6 is not tested for this repo, the version we used is 0.2.4. Also, if you meet some problem when `from nncore.engine import load_checkpoint, set_random_seed` is in the try except module, it seems that there's something wrong in your mmcv/mmdet.

**Comment by PradKalkar** [comment]
Hi. Thanks for the docs. I am getting the same error as faced by two others - NameError: name 'load_checkpoint' is not defined. I did install consnet from the source and didn't do pip install consnet. Also, I checked the versions of pytorch, mmdet and nncore - they are 1.8.1+cu102, 2.11.0 and 0.2.4 respectively. Could you please help?

**Comment by yeliudev** [comment]
> Hi. Thanks for the docs. I am getting the same error as faced by two others - NameError: name 'load_checkpoint' is not defined. I did install consnet from the source and didn't do pip install consnet. Also, I checked the versions of pytorch, mmdet and nncore - they are 1.8.1+cu102, 2.11.0 and 0.2.4 respectively. Could you please help?

Thanks for your feedback. May I ask that did you install consnet from source using `pip install -e .[full]` ranther than `pip install -e .`? You may also try to modify the code [here](https://github.com/yeliudev/ConsNet/blob/main/consnet/models/builder.py#L13:L20) by moving the imports out of try...except to see which line raises the error.

**Comment by PradKalkar** [comment]
Hi. Thank you @yeliudev for the reply. 
I installed consnet from the source using the first command you mentioned - pip install -e .[full]
I tried removing the try-except block, but I was facing another error. I will send here the screenshot of the error in some time, as currently I am not having access to that computer.

**Comment by PradKalkar** [comment]
ModuleNotFoundError: No module named 'mmcv._ext'
This is the error which I am facing after removing the try except block.
PFA the traceback below.

![image](https://user-images.githubusercontent.com/52340022/208500322-a6acc89a-b151-478a-bee3-f5187361a645.png)
![image](https://user-images.githubusercontent.com/52340022/208500670-024474e4-79e3-4c8e-9164-85d620bc1180.png)

**Comment by PradKalkar** [comment]
Also @yeliudev may I ask that what is the object detection mAP (not the HOI mAP using the complete model) on the HICO-DET test set of the two object detectors which you used - first one pretrained on COCO and the other one finetuned on HICO-DET?

**Comment by yeliudev** [comment]
> ModuleNotFoundError: No module named 'mmcv._ext' This is the error which I am facing after removing the try except block. PFA the traceback below.
> 
> ![image](https://user-images.githubusercontent.com/52340022/208500322-a6acc89a-b151-478a-bee3-f5187361a645.png) ![image](https://user-images.githubusercontent.com/52340022/208500670-024474e4-79e3-4c8e-9164-85d620bc1180.png)

This means that you are using `mmcv` instead of `mmcv-full`. So that the CUDA extensions are not compiled. You may try to re-install this package.

**Comment by yeliudev** [comment]
> Also @yeliudev may I ask that what is the object detection mAP (not the HOI mAP using the complete model) on the HICO-DET test set of the two object detectors which you used - first one pretrained on COCO and the other one finetuned on HICO-DET?

I'm not pretty sure since this project was finished years ago. I remember that the mAP of COCO detector was about 13, and the HICO-DET finetuned one shall be about 20.

**Comment by PradKalkar** [comment]
> > Also @yeliudev may I ask that what is the object detection mAP (not the HOI mAP using the complete model) on the HICO-DET test set of the two object detectors which you used - first one pretrained on COCO and the other one finetuned on HICO-DET?
> 
> I'm not pretty sure since this project was finished years ago. I remember that the mAP of COCO detector was about 13, and the HICO-DET finetuned one shall be about 20.

Thanks for your response @yeliudev.

**Comment by PradKalkar** [comment]
> > ModuleNotFoundError: No module named 'mmcv._ext' This is the error which I am facing after removing the try except block. PFA the traceback below.
> > ![image](https://user-images.githubusercontent.com/52340022/208500322-a6acc89a-b151-478a-bee3-f5187361a645.png) ![image](https://user-images.githubusercontent.com/52340022/208500670-024474e4-79e3-4c8e-9164-85d620bc1180.png)
> 
> This means that you are using `mmcv` instead of `mmcv-full`. So that the CUDA extensions are not compiled. You may try to re-install this package.

But, I installed it using the pip install command given in your docs. Also, I tried to uninstall mmcv but upon doing that it says mmcv not found, which means that mmcv-full was installed. Would you please help? 
Also, what version of cudatoolkit-dev did you use in your conda environment? Here https://anaconda.org/conda-forge/cudatoolkit-dev/files?page=2 it shows that cudatoolkit-dev version 10.2 doesn't exists.

**Comment by yeliudev** [comment]
There are two versions of mmcv, one is called `mmcv` and the other shall be `mmcv-full`. You may try to manually install it by using `pip install mmcv-full` and see if the CUDA extensions are compiled correctly. We did not use cudatoolkit-dev in our env. We installed CUDA from scratch in our system.

**Comment by PradKalkar** [comment]
Thanks for the reply. Would you please check and share the exact version of your mmcv-full?

**Comment by yeliudev** [comment]
1.3.8

**Comment by PradKalkar** [comment]
Thanks for sharing the version. I will check by installing this version on the system. Also, will the CUDA version matter? I don't have 10.2 in my system. Is the issue coming because of that?

**Comment by yeliudev** [comment]
I don't think the CUDA version matters. Compiling `mmcv-full` using your own CUDA shall be fine. Please feel free to leave a message here if you meet any other problems.

**Comment by PradKalkar** [comment]
Would you please clarify the meaning of "compiling" mmcv-full using your own CUDA? Is compiling a separate step to be done after installing mmcv-full? If yes, would you please share the command for doing so.

**Comment by yeliudev** [comment]
Simply running `pip install mmcv-full==1.3.8` should compile it automatically. Please be check that if there is any error during the installation.

**Comment by PradKalkar** [comment]
Thanks for your quick responses @yeliudev.

**Comment by PradKalkar** [comment]
Hi. I was able to resolve the mmcv error. But, now I am encountering another error. I installed the packages as follows - 
1. pip install torch==1.8.1+cu111 torchvision==0.9.1+cu111 torchaudio==0.8.1 -f https://download.pytorch.org/whl/torch_stable.html
2. pip install -U openmim
mim install mmcv-full==1.3.8
pip install mmdet==2.11.0
3. pip install nncore==0.2.4

With the above 3 steps, the command of python tools/build_dataset.py started executing correctly and the hdf5 files were making up (i.e. the detection step and extraction of features). But allennlp wasn't installed. So, once I understood that mmcv is working fine, I interrupted the above execution. Then, I installed allenlp using - 

4. pip install allennlp==2.2.0

After this, I again ran the same command (python tools/build_dataset.py), but it errored out. Attaching the traceback below.
Will the above command (python tools/build_dataset.py) work even without installing allennlp? Or will it require allennlp to be installed? I assume that build_graph function in the file won't work without allennlp. Is it right?

![image](https://user-images.githubusercontent.com/52340022/208693015-c6d214ea-50f4-4631-9580-1ede9984b176.png)
![image](https://user-images.githubusercontent.com/52340022/208693394-6f42e30a-6b29-44c5-8e0f-2e03bbb19986.png)

**Comment by yeliudev** [comment]
It seems that the version of package `transformers` is not correct. Could you install `transformers==0.11` and try it again?

**Comment by PradKalkar** [comment]
> It seems that the version of package `transformers` is not correct. Could you install `transformers==0.11` and try it again?

Getting this when trying to install it. :(
![image](https://user-images.githubusercontent.com/52340022/208743424-2ce8fe80-9097-44dd-8cfd-f23c73082f06.png)
